In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("TotalDF1.csv")

In [3]:
df.sort_values(["Player"])

,Player,Overall Score,Potential Score,Market Value,Weekly Salary,Height,Weight,Age,Preferred Foot,id,...,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,year
4824,Aaron Cresswell,74,76,3300000.0,35000.0,170,66,26,Left,534,...,17,2,1,D M S,West Ham,0,0.585906,5.244608,3.410585,2016
10135,Aaron Cresswell,76,76,6000000.0,65000.0,175,66,29,Left,534,...,26,7,0,D,West Ham,3,1.032538,6.834942,4.891464,2019
8603,Aaron Cresswell,74,75,5500000.0,70000.0,170,66,28,Left,534,...,17,1,0,D S,West Ham,0,0.419239,2.039328,1.581602,2018
11883,Aaron Cresswell,76,76,6500000.0,65000.0,175,66,30,Left,534,...,26,0,0,D,West Ham,0,0.475528,5.247772,4.425913,2020
1476,Aaron Cresswell,70,79,NaN,NaN,170,66,24,Left,534,...,35,5,0,D,West Ham,2,1.242632,9.588578,6.953860,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3787,Özkan Yildirim,66,76,675000.0,5000.0,173,73,22,Left,2646,...,0,0,0,S,Werder Bremen,0,0.083136,0.083136,0.000000,2015
1728,Özkan Yildirim,67,77,675000.0,NaN,172,76,21,Left,2646,...,0,0,0,M,Werder Bremen,0,0.000000,0.013800,0.013800,2014
10720,Ørjan Nyland,72,72,2100000.0,11000.0,192,90,29,Right,250,...,0,0,0,GK S,Aston Villa,0,0.000000,0.194507,0.194507,2019
5010,Ørjan Nyland,73,75,NaN,35000.0,192,90,26,Right,250,...,0,0,0,GK S,Ingolstadt,0,0.000000,0.593702,0.593702,2016
2908,Ørjan Nyland,73,81,2100000.0,35000.0,192,78,25,Right,250,...,0,0,0,GK,Ingolstadt,0,0.000000,0.167960,0.167960,2015

In [4]:
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', None)

In [6]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
12683    False
12684    False
12685    False
12686    False
12687    False
Length: 12688, dtype: bool

In [7]:
df.shape

(12688, 28)

In [9]:
df.drop_duplicates(keep='first', inplace=True)
df.shape

(12419, 28)

In [10]:
df.drop(axis = 1, columns=['player_name', 'team_title', 'position'], inplace=True)
df['Preferred Foot'].replace({"Right": 0, "Left": 1}, inplace=True)

In [11]:
df.dropna(inplace=True)
df.sort_values("Market Value", ascending=False)

,Player,Overall Score,Potential Score,Market Value,Weekly Salary,Height,Weight,Age,Preferred Foot,id,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup,year
7389,Neymar,92,93,119500000.0,280000.0,175,68,26,0,2099,17,1443,15,11.895758,7,7.784678,55,43,2,0,10,8.095414,18.165200,6.617415,2018
7387,Lionel Messi,94,94,118500000.0,560000.0,170,72,31,1,2097,34,2704,36,25.997169,13,15.335166,170,93,3,0,32,22.280909,38.459877,10.698799,2018
9197,Lionel Messi,94,94,110500000.0,560000.0,170,72,32,1,2097,33,2876,25,20.849667,20,16.593363,159,88,4,0,20,17.133279,34.923467,13.537658,2019
5600,Neymar,92,94,106000000.0,450000.0,175,68,25,0,2099,20,1797,19,16.537796,13,12.280968,91,70,4,1,15,13.497416,31.428769,11.523155,2017
7392,Kevin De Bruyne,91,92,104500000.0,390000.0,181,68,27,0,447,19,965,2,1.474241,2,6.654021,31,36,2,0,2,1.474241,12.202199,8.481830,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11165,Gianluigi Buffon,83,83,1000.0,60000.0,192,92,42,0,1285,4,360,0,0.000000,0,0.000000,0,0,0,0,0,0.000000,1.360817,1.360817,2020
6130,Hilton,79,79,1000.0,26000.0,180,78,40,0,3337,27,2430,0,1.320150,0,0.339829,20,8,5,0,0,1.320150,4.734427,4.612287,2017
6569,Gareth McAuley,76,76,1000.0,29000.0,195,89,37,0,806,9,454,0,0.000000,0,0.000000,0,0,0,0,0,0.000000,0.281384,0.281384,2017
9267,Gianluigi Buffon,86,86,1000.0,60000.0,192,92,41,0,1285,9,810,0,0.000000,0,0.026923,0,1,0,0,0,0.000000,1.617574,1.590651,2019
12314,Cifuentes,73,73,1000.0,4000.0,189,80,41,0,2350,2,69,0,0.018400,0,0.000000,1,0,0,0,0,0.018400,0.075165,0.075165,2020

In [92]:
df.to_csv(r'C:\Users\user\project\FinalDF.csv', index=False)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11207 entries, 0 to 12687
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player           11207 non-null  object
 1   Overall Score    11207 non-null  int64
 2   Potential Score  11207 non-null  int64
 3   Market Value     11207 non-null  float64
 4   Weekly Salary    11207 non-null  float64
 5   Height           11207 non-null  int64
 6   Weight           11207 non-null  int64
 7   Age              11207 non-null  int64
 8   Preferred Foot   11207 non-null  int64
 9   id               11207 non-null  int64
 10  games            11207 non-null  int64
 11  time             11207 non-null  int64
 12  goals            11207 non-null  int64
 13  xG               11207 non-null  float64
 14  assists          11207 non-null  int64
 15  xA               11207 non-null  float64
 16  shots            11207 non-null  int64
 17  key_passes       11207 non-null  int64
 18  yellow_cards     11207 non-null  int64
 19  red_cards        11207 non-null  int64
 20  npg              11207 non-null  int64
 21  npxG             11207 non-null  float64
 22  xGChain          11207 non-null  float64
 23  xGBuildup        11207 non-null  float64
 24  year             11207 non-null  int64
dtypes: float64(7), int64(17), object(1)
memory usage: 2.2+ MB